variable "resource_group_name" {}
variable "resource_group_location" {}
variable "key_vault_name" {}
variable "azurerm_storage_account" {}
variable "sku_name" {}
variable "enabled_for_disk_encryption" {}
variable "soft_delete_retention_days" {}
variable "purge_protection_enabled" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "min_tls_version" {}
